[package]
name = "texine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"

[dependencies.sdl2]
version = "0.36"
default-features = false
features = ["ttf"]
